package com.dbs.spring.utils;

public class PaymentsDatabaseInitializer {
	public static final boolean BUILD_DB = true;
	public static String BANKSJSON = "[\n"
			+ "        {\n"
			+ "            \"bic\": \"ABBLINBBXXX\",\n"
			+ "            \"bankname\": \"AB BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ACBLINBBXXX\",\n"
			+ "            \"bankname\": \"ABHYUDAYA CO-OPERATIVE BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ABNAINBBAHM\",\n"
			+ "            \"bankname\": \"ABN AMRO BANK N.V.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ADCBINBBXXX\",\n"
			+ "            \"bankname\": \"ABU DHABI COMMERCIAL BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ALLAINBBXXX\",\n"
			+ "            \"bankname\": \"ALLAHABAD BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ANDBINBBXXX\",\n"
			+ "            \"bankname\": \"ANDHRA BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ADIAINBBXXX\",\n"
			+ "            \"bankname\": \"ANTWERP DIAMOND BANK N.V.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"AXISINBBXXX\",\n"
			+ "            \"bankname\": \"AXIS BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BOFAIN4XMAA\",\n"
			+ "            \"bankname\": \"BANK OF AMERICA, N.A. CHENNAI\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BOFAIN4XCCU\",\n"
			+ "            \"bankname\": \"BANK OF AMERICA, N.A. KOLKATA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BBKUINBBXXX\",\n"
			+ "            \"bankname\": \"BANK OF BAHRAIN AND KUWAIT B.S.C.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BARBINBBXXX\",\n"
			+ "            \"bankname\": \"BANK OF BARODA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BCEYIN5MXXX\",\n"
			+ "            \"bankname\": \"BANK OF CEYLON\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BKIDINBBXXX\",\n"
			+ "            \"bankname\": \"BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"MAHBINBBAHM\",\n"
			+ "            \"bankname\": \"BANK OF MAHARASHTRA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"NOSCINBBBLR\",\n"
			+ "            \"bankname\": \"BANK OF NOVA SCOTIA, THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BOTKIN5MXXX\",\n"
			+ "            \"bankname\": \"BANK OF TOKYO-MITSUBISHI UFJ, LTD., THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BARCINBBMUM\",\n"
			+ "            \"bankname\": \"BARCLAYS BANK PLC\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BNPAINBBAHM\",\n"
			+ "            \"bankname\": \"BNP PARIBAS INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CNRBINBBXXX\",\n"
			+ "            \"bankname\": \"CANARA BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CSYBIN55XXX\",\n"
			+ "            \"bankname\": \"CATHOLIC SYRIAN BANK LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CBININBBLAL\",\n"
			+ "            \"bankname\": \"CENTRAL BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CTCBINDDXXX\",\n"
			+ "            \"bankname\": \"CHINATRUST COMMERCIAL BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CITIINBXBLR\",\n"
			+ "            \"bankname\": \"CITIBANK N.A.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CIUBIN5MXXX\",\n"
			+ "            \"bankname\": \"CITY UNION BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CCILINBBXXX\",\n"
			+ "            \"bankname\": \"CLEARING CORPORATION OF INDIA LTD, THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CORPINBBXXX\",\n"
			+ "            \"bankname\": \"CORPORATION BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"DBSSINBBIBD\",\n"
			+ "            \"bankname\": \"DBS BANK LTD, MUMBAI BRANCH\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BKDNINBBXXX\",\n"
			+ "            \"bankname\": \"DENA BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"DEUTINBBBGL\",\n"
			+ "            \"bankname\": \"DEUTSCHE BANK AG\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"DCBLINBB036\",\n"
			+ "            \"bankname\": \"DEVELOPMENT CREDIT BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"DLXBINBBKPM\",\n"
			+ "            \"bankname\": \"DHANALAKSHMI BANK LTD, THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"EIBIINBBXXX\",\n"
			+ "            \"bankname\": \"EXPORT-IMPORT BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"FDRLINBBXXX\",\n"
			+ "            \"bankname\": \"FEDERAL BANK LIMITED, THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"FIRNINBBXXX\",\n"
			+ "            \"bankname\": \"FIRSTRAND BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"HDFCINBBAHM\",\n"
			+ "            \"bankname\": \"HDFC BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"HSBCINBBBGE\",\n"
			+ "            \"bankname\": \"HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED, THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"ICICINBB024\",\n"
			+ "            \"bankname\": \"ICICI BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"IBKLINBBXXX\",\n"
			+ "            \"bankname\": \"IDBI BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"IDIBINBBXXX\",\n"
			+ "            \"bankname\": \"INDIAN BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"IOBAINBBXXX\",\n"
			+ "            \"bankname\": \"INDIAN OVERSEAS BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"INDBINBBXXX\",\n"
			+ "            \"bankname\": \"INDUSIND BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"VYSAINBBAHD\",\n"
			+ "            \"bankname\": \"ING VYSYA BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"JAKAINBBAGR\",\n"
			+ "            \"bankname\": \"JAMMU AND KASHMIR BANK LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"CHASINBXTRO\",\n"
			+ "            \"bankname\": \"JPMORGAN CHASE BANK, N.A.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"VTBRINDDXXX\",\n"
			+ "            \"bankname\": \"JSC VTB BANK, NEW DELHI BRANCH\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"KARBINBBBNG\",\n"
			+ "            \"bankname\": \"KARNATAKA BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"KVBLINBBADI\",\n"
			+ "            \"bankname\": \"KARUR VYSYA BANK LTD., THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"KKBKINBBCPC\",\n"
			+ "            \"bankname\": \"KOTAK MAHINDRA BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"KRTHINBBXXX\",\n"
			+ "            \"bankname\": \"KRUNG THAI BANK PUBLIC COMPANY LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"LAVBINBB114\",\n"
			+ "            \"bankname\": \"LAKSHMI VILAS BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"MSCIINBBXXX\",\n"
			+ "            \"bankname\": \"MAHARASHTRA STATE CO-OPERATIVE BANK LTD., THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"MSHQINBBXXX\",\n"
			+ "            \"bankname\": \"MASHREQ BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"MHCBINBBXXX\",\n"
			+ "            \"bankname\": \"MIZUHO CORPORATE BANK LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"MSMBINBXXXX\",\n"
			+ "            \"bankname\": \"MORGAN STANLEY INDIA COMPANY PVT LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"OIBAINBBXXX\",\n"
			+ "            \"bankname\": \"OMAN INTERNATIONAL BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"GTBKINBBXXX\",\n"
			+ "            \"bankname\": \"ORIENTAL BANK OF COMMERCE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"PSIBINBB020\",\n"
			+ "            \"bankname\": \"PUNJAB AND SIND BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"PUNBINBBXXX\",\n"
			+ "            \"bankname\": \"PUNJAB NATIONAL BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"RBISINBBXXX\",\n"
			+ "            \"bankname\": \"RESERVE BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SRCBINBBAUR\",\n"
			+ "            \"bankname\": \"SARASWAT CO-OPERATIVE BANK LTD., THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBCLINBBXXX\",\n"
			+ "            \"bankname\": \"SBI COMMERCIAL AND INTERNATIONAL BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SHBKINBBXXX\",\n"
			+ "            \"bankname\": \"SHINHAN BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SIDBINBBCBB\",\n"
			+ "            \"bankname\": \"SMALL INDUSTRIES DEVELOPMENT BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SOGEINBBBLR\",\n"
			+ "            \"bankname\": \"SOCIETE GENERALE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BSONINCCXXX\",\n"
			+ "            \"bankname\": \"SONALI BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SOININ55179\",\n"
			+ "            \"bankname\": \"SOUTH INDIAN BANK LTD., THE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SCDIIN51XXX\",\n"
			+ "            \"bankname\": \"SPARK CAPITAL ADVISORS (INDIA) PRIVATE LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SCBLINBBMDS\",\n"
			+ "            \"bankname\": \"STANDARD CHARTERED BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBBJINBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF BIKANER AND JAIPUR\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBHYINBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF HYDERABAD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBININBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"STININBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF INDORE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"STCBINBXNPT\",\n"
			+ "            \"bankname\": \"STATE BANK OF MAURITIUS LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBMYINBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF MYSORE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"STBPINBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF PATIALA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SBTRINBBXXX\",\n"
			+ "            \"bankname\": \"STATE BANK OF TRAVANCORE\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SYNBINBBXXX\",\n"
			+ "            \"bankname\": \"SYNDICATE BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"TMBLINBBCHE\",\n"
			+ "            \"bankname\": \"TAMILNAD MERCANTILE BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BRAJINBBARA\",\n"
			+ "            \"bankname\": \"THE BANK OF RAJASTHAN LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"BCMLINBBXXX\",\n"
			+ "            \"bankname\": \"THE BHARAT CO-OPERATIVE BANK (MUMBAI) LTD\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"COSDINBBXXX\",\n"
			+ "            \"bankname\": \"THE COSMOS CO-OPERATIVE BANK LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"KALUINAAXXX\",\n"
			+ "            \"bankname\": \"THE KALUPUR COMMERCIAL CO-OPERATIVE BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"SVCBINBBBLR\",\n"
			+ "            \"bankname\": \"THE SHAMRAO VITHAL CO-OPERATIVE BANK LIMITED\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"TCILINBBXXX\",\n"
			+ "            \"bankname\": \"THOMAS COOK (INDIA) LTD.\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"UBSWINBBXXX\",\n"
			+ "            \"bankname\": \"UBS AG\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"UCBAINBBXXX\",\n"
			+ "            \"bankname\": \"UCO BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"UBININBBXXX\",\n"
			+ "            \"bankname\": \"UNION BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"UTBIINBBECB\",\n"
			+ "            \"bankname\": \"UNITED BANK OF INDIA\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"VIJBINBBXXX\",\n"
			+ "            \"bankname\": \"VIJAYA BANK\"\n"
			+ "        },\n"
			+ "        {\n"
			+ "            \"bic\": \"YESBINBBDEL\",\n"
			+ "            \"bankname\": \"YES BANK LIMITED\"\n"
			+ "        }\n"
			+ "    ]";

	public static String CUSTOMERJSON= "[\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"83020817828620\",\r\n"
			+ "            \"accountholdername\": \"A KRISHNA MOHAN\",\r\n"
			+ "            \"clearbalance\": \"56000\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"71319440983198\",\r\n"
			+ "            \"accountholdername\": \"A M MAYANNA\",\r\n"
			+ "            \"clearbalance\": \"224000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"69652133523248\",\r\n"
			+ "            \"accountholdername\": \"HDFC BANK -(CHENNAI)\",\r\n"
			+ "            \"clearbalance\": \"223997\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"78195245302715\",\r\n"
			+ "            \"accountholdername\": \"A RAJESH KUMAR\",\r\n"
			+ "            \"clearbalance\": \"35000\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"47468155457802\",\r\n"
			+ "            \"accountholdername\": \"A S VIJAY KUMAR\",\r\n"
			+ "            \"clearbalance\": \"56000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"45766734966995\",\r\n"
			+ "            \"accountholdername\": \"ABHISHEK BIYANI\",\r\n"
			+ "            \"clearbalance\": \"224000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"87139550565094\",\r\n"
			+ "            \"accountholdername\": \"ABHITHA\",\r\n"
			+ "            \"clearbalance\": \"223997\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"39145971759304\",\r\n"
			+ "            \"accountholdername\": \"ABRAHAM VARGHESE\",\r\n"
			+ "            \"clearbalance\": \"5200\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"83411975607693\",\r\n"
			+ "            \"accountholdername\": \"ABY GEORGE\",\r\n"
			+ "            \"clearbalance\": \"15400\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"45002608912874\",\r\n"
			+ "            \"accountholdername\": \"HDFC BANK -(MUMBAI)\",\r\n"
			+ "            \"clearbalance\": \"56001\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"15510851190541\",\r\n"
			+ "            \"accountholdername\": \"AJAY SHAMU KUMAR\",\r\n"
			+ "            \"clearbalance\": \"224004\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"64059555180495\",\r\n"
			+ "            \"accountholdername\": \"AKSHAYA WEALTH MANAGEMENT (P) LTD\",\r\n"
			+ "            \"clearbalance\": \"224001\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"42895235807723\",\r\n"
			+ "            \"accountholdername\": \"HDFC BANK -(DELHI)\",\r\n"
			+ "            \"clearbalance\": \"1120005\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"34835543999244\",\r\n"
			+ "            \"accountholdername\": \"ANAND L S\",\r\n"
			+ "            \"clearbalance\": \"56001\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"76396804083946\",\r\n"
			+ "            \"accountholdername\": \"ANANTHAKUMAR\",\r\n"
			+ "            \"clearbalance\": \"224004\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"14783038759432\",\r\n"
			+ "            \"accountholdername\": \"ANANTHAMURTHY SHAMASUNDARA\",\r\n"
			+ "            \"clearbalance\": \"100\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"87030077359017\",\r\n"
			+ "            \"accountholdername\": \"ANIL GUPTA\",\r\n"
			+ "            \"clearbalance\": \"25600\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"37437137526069\",\r\n"
			+ "            \"accountholdername\": \"ANIL KUMAR\",\r\n"
			+ "            \"clearbalance\": \"35800\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"69443662887399\",\r\n"
			+ "            \"accountholdername\": \"ANIL KUMAR NAGARAJ\",\r\n"
			+ "            \"clearbalance\": \"56001\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"27216037942722\",\r\n"
			+ "            \"accountholdername\": \"HDFC BANK -(GOA)\",\r\n"
			+ "            \"clearbalance\": \"224004\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"77236671175938\",\r\n"
			+ "            \"accountholdername\": \"ANIL V GORUR\",\r\n"
			+ "            \"clearbalance\": \"224001\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"79594243111085\",\r\n"
			+ "            \"accountholdername\": \"ANITA B MEHTA\",\r\n"
			+ "            \"clearbalance\": \"-25000\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"46957845854316\",\r\n"
			+ "            \"accountholdername\": \"ANITHA B ASHWATH\",\r\n"
			+ "            \"clearbalance\": \"56001\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"61331727051606\",\r\n"
			+ "            \"accountholdername\": \"ANJAN KUMAR G\",\r\n"
			+ "            \"clearbalance\": \"224004\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"64754104823235\",\r\n"
			+ "            \"accountholdername\": \"ANKITA BANERJEE\",\r\n"
			+ "            \"clearbalance\": \"224001\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"80505259371358\",\r\n"
			+ "            \"accountholdername\": \"ANNUKA NIRVAN\",\r\n"
			+ "            \"clearbalance\": \"76334\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"63615912257030\",\r\n"
			+ "            \"accountholdername\": \"ANU\",\r\n"
			+ "            \"clearbalance\": \"76334\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"13645221972859\",\r\n"
			+ "            \"accountholdername\": \"ANUPAMA N\",\r\n"
			+ "            \"clearbalance\": \"95000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"17308739433267\",\r\n"
			+ "            \"accountholdername\": \"AREEFIKBAL T F\",\r\n"
			+ "            \"clearbalance\": \"65000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"57577094248867\",\r\n"
			+ "            \"accountholdername\": \"ARJUN PARAMESWARA\",\r\n"
			+ "            \"clearbalance\": \"508250\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"89479615455884\",\r\n"
			+ "            \"accountholdername\": \"ARPITHA M S\",\r\n"
			+ "            \"clearbalance\": \"-350\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"27225043545104\",\r\n"
			+ "            \"accountholdername\": \"ASADI LINGAREDDY\",\r\n"
			+ "            \"clearbalance\": \"1556002\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"20050293665889\",\r\n"
			+ "            \"accountholdername\": \"ASHAJYOTHI M\",\r\n"
			+ "            \"clearbalance\": \"224008\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"81181212472499\",\r\n"
			+ "            \"accountholdername\": \"ASHISH MISHRA\",\r\n"
			+ "            \"clearbalance\": \"224005\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"71928505646815\",\r\n"
			+ "            \"accountholdername\": \"ASHOK H R\",\r\n"
			+ "            \"clearbalance\": \"46000\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"49823469696097\",\r\n"
			+ "            \"accountholdername\": \"ASHOKA AR\",\r\n"
			+ "            \"clearbalance\": \"56200\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"98196009547795\",\r\n"
			+ "            \"accountholdername\": \"AVISHEK MUKHERJEE\",\r\n"
			+ "            \"clearbalance\": \"56002\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"79029264231605\",\r\n"
			+ "            \"accountholdername\": \"AYISHA KAUSAR\",\r\n"
			+ "            \"clearbalance\": \"224008\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"53853797183656\",\r\n"
			+ "            \"accountholdername\": \"B A SANTOSH\",\r\n"
			+ "            \"clearbalance\": \"224005\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"57792220815896\",\r\n"
			+ "            \"accountholdername\": \"B JAYARAM\",\r\n"
			+ "            \"clearbalance\": \"1120025\",\r\n"
			+ "            \"overdraftflag\": \"false\"\r\n"
			+ "        },\r\n"
			+ "        {\r\n"
			+ "            \"customerid\": \"72153770404022\",\r\n"
			+ "            \"accountholdername\": \"B PRAKASH BABU\",\r\n"
			+ "            \"clearbalance\": \"0\",\r\n"
			+ "            \"overdraftflag\": \"true\"\r\n"
			+ "        }\r\n"
			+ "    ]";
	
}
